// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dimensions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDepartments = `-- name: CountDepartments :one
SELECT COUNT(*) FROM departments
`

func (q *Queries) CountDepartments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroups = `-- name: CountGroups :one
SELECT COUNT(*) FROM groups
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegions = `-- name: CountRegions :one
SELECT COUNT(*) FROM regions
`

func (q *Queries) CountRegions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRegions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoles = `-- name: CountRoles :one
SELECT COUNT(*) FROM roles
`

func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (id, name, description, permission_number, org_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, permission_number, org_id, created_at, updated_at
`

type CreateDepartmentParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Description      pgtype.Text `json:"description"`
	PermissionNumber pgtype.Int2 `json:"permission_number"`
	OrgID            pgtype.UUID `json:"org_id"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PermissionNumber,
		arg.OrgID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, description, permission_number, org_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, permission_number, org_id, created_at, updated_at
`

type CreateGroupParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Description      pgtype.Text `json:"description"`
	PermissionNumber pgtype.Int2 `json:"permission_number"`
	OrgID            pgtype.UUID `json:"org_id"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PermissionNumber,
		arg.OrgID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRegion = `-- name: CreateRegion :one
INSERT INTO regions (id, name, description, permission_number, org_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, permission_number, org_id, created_at, updated_at
`

type CreateRegionParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Description      pgtype.Text `json:"description"`
	PermissionNumber pgtype.Int2 `json:"permission_number"`
	OrgID            pgtype.UUID `json:"org_id"`
}

func (q *Queries) CreateRegion(ctx context.Context, arg CreateRegionParams) (Region, error) {
	row := q.db.QueryRow(ctx, createRegion,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PermissionNumber,
		arg.OrgID,
	)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, name, description, permission_number, org_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, permission_number, org_id, created_at, updated_at
`

type CreateRoleParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Description      pgtype.Text `json:"description"`
	PermissionNumber pgtype.Int2 `json:"permission_number"`
	OrgID            pgtype.UUID `json:"org_id"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PermissionNumber,
		arg.OrgID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepartment, id)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const deleteRegion = `-- name: DeleteRegion :exec
DELETE FROM regions WHERE id = $1
`

func (q *Queries) DeleteRegion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRegion, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM departments WHERE id = $1
`

// Departments
func (q *Queries) GetDepartment(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartmentByName = `-- name: GetDepartmentByName :one
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM departments WHERE name = $1 AND org_id = $2
`

type GetDepartmentByNameParams struct {
	Name  string      `json:"name"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetDepartmentByName(ctx context.Context, arg GetDepartmentByNameParams) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByName, arg.Name, arg.OrgID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM groups WHERE id = $1
`

// Groups
func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM groups WHERE name = $1 AND org_id = $2
`

type GetGroupByNameParams struct {
	Name  string      `json:"name"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetGroupByName(ctx context.Context, arg GetGroupByNameParams) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByName, arg.Name, arg.OrgID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextDepartmentPermissionNumber = `-- name: GetNextDepartmentPermissionNumber :one
SELECT COALESCE(MAX(permission_number), 0) + 1 FROM departments FOR UPDATE
`

func (q *Queries) GetNextDepartmentPermissionNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextDepartmentPermissionNumber)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getNextGroupPermissionNumber = `-- name: GetNextGroupPermissionNumber :one
SELECT COALESCE(MAX(permission_number), 0) + 1 FROM groups FOR UPDATE
`

func (q *Queries) GetNextGroupPermissionNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextGroupPermissionNumber)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getNextRegionPermissionNumber = `-- name: GetNextRegionPermissionNumber :one
SELECT COALESCE(MAX(permission_number), 0) + 1 FROM regions FOR UPDATE
`

func (q *Queries) GetNextRegionPermissionNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextRegionPermissionNumber)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getNextRolePermissionNumber = `-- name: GetNextRolePermissionNumber :one
SELECT COALESCE(MAX(permission_number), 0) + 1 FROM roles FOR UPDATE
`

func (q *Queries) GetNextRolePermissionNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextRolePermissionNumber)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getRegion = `-- name: GetRegion :one
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM regions WHERE id = $1
`

// Regions
func (q *Queries) GetRegion(ctx context.Context, id pgtype.UUID) (Region, error) {
	row := q.db.QueryRow(ctx, getRegion, id)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegionByName = `-- name: GetRegionByName :one
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM regions WHERE name = $1 AND org_id = $2
`

type GetRegionByNameParams struct {
	Name  string      `json:"name"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetRegionByName(ctx context.Context, arg GetRegionByNameParams) (Region, error) {
	row := q.db.QueryRow(ctx, getRegionByName, arg.Name, arg.OrgID)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM roles WHERE id = $1
`

// Roles
func (q *Queries) GetRole(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM roles WHERE name = $1 AND org_id = $2
`

type GetRoleByNameParams struct {
	Name  string      `json:"name"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, arg.Name, arg.OrgID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM departments ORDER BY name LIMIT $1 OFFSET $2
`

type ListDepartmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PermissionNumber,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM groups ORDER BY name LIMIT $1 OFFSET $2
`

type ListGroupsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PermissionNumber,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegions = `-- name: ListRegions :many
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM regions ORDER BY name LIMIT $1 OFFSET $2
`

type ListRegionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRegions(ctx context.Context, arg ListRegionsParams) ([]Region, error) {
	rows, err := q.db.Query(ctx, listRegions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PermissionNumber,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, permission_number, org_id, created_at, updated_at FROM roles ORDER BY name LIMIT $1 OFFSET $2
`

type ListRolesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PermissionNumber,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, permission_number, org_id, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment, arg.ID, arg.Name, arg.Description)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, permission_number, org_id, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRegion = `-- name: UpdateRegion :one
UPDATE regions SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, permission_number, org_id, created_at, updated_at
`

type UpdateRegionParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateRegion(ctx context.Context, arg UpdateRegionParams) (Region, error) {
	row := q.db.QueryRow(ctx, updateRegion, arg.ID, arg.Name, arg.Description)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, permission_number, org_id, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PermissionNumber,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
