// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDocumentTag = `-- name: AddDocumentTag :exec
INSERT INTO document_tags (document_id, tag_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddDocumentTagParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	TagID      pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddDocumentTag(ctx context.Context, arg AddDocumentTagParams) error {
	_, err := q.db.Exec(ctx, addDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const clearDocumentTags = `-- name: ClearDocumentTags :exec
DELETE FROM document_tags WHERE document_id = $1
`

func (q *Queries) ClearDocumentTags(ctx context.Context, documentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDocumentTags, documentID)
	return err
}

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*) FROM documents
`

func (q *Queries) CountDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByFolder = `-- name: CountDocumentsByFolder :one
SELECT COUNT(*) FROM documents WHERE folder_id = $1
`

func (q *Queries) CountDocumentsByFolder(ctx context.Context, folderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByFolder, folderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsForFolders = `-- name: CountDocumentsForFolders :one
SELECT COUNT(*) FROM documents
WHERE org_id = $1 AND (folder_id = ANY($2::uuid[]) OR (folder_id IS NULL AND $3 = true))
`

type CountDocumentsForFoldersParams struct {
	OrgID   pgtype.UUID   `json:"org_id"`
	Column2 []pgtype.UUID `json:"column_2"`
	Column3 interface{}   `json:"column_3"`
}

func (q *Queries) CountDocumentsForFolders(ctx context.Context, arg CountDocumentsForFoldersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsForFolders, arg.OrgID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsForOrg = `-- name: CountDocumentsForOrg :one
SELECT COUNT(*) FROM documents WHERE org_id = $1
`

func (q *Queries) CountDocumentsForOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsForOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsWithNullFolder = `-- name: CountDocumentsWithNullFolder :one
SELECT COUNT(*) FROM documents WHERE org_id = $1 AND folder_id IS NULL
`

func (q *Queries) CountDocumentsWithNullFolder(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsWithNullFolder, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id, title, description, text, document_key, document_url,
    processing_status, processing_details, metadata, use_knowledge_graph,
    org_id, folder_id, uploaded_by_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, title, description, text, document_key, document_url, processing_status, processing_details, metadata, use_knowledge_graph, org_id, folder_id, uploaded_by_id, created_at, updated_at
`

type CreateDocumentParams struct {
	ID                pgtype.UUID `json:"id"`
	Title             string      `json:"title"`
	Description       pgtype.Text `json:"description"`
	Text              pgtype.Text `json:"text"`
	DocumentKey       string      `json:"document_key"`
	DocumentUrl       pgtype.Text `json:"document_url"`
	ProcessingStatus  pgtype.Text `json:"processing_status"`
	ProcessingDetails []byte      `json:"processing_details"`
	Metadata          []byte      `json:"metadata"`
	UseKnowledgeGraph pgtype.Bool `json:"use_knowledge_graph"`
	OrgID             pgtype.UUID `json:"org_id"`
	FolderID          pgtype.UUID `json:"folder_id"`
	UploadedByID      pgtype.UUID `json:"uploaded_by_id"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Text,
		arg.DocumentKey,
		arg.DocumentUrl,
		arg.ProcessingStatus,
		arg.ProcessingDetails,
		arg.Metadata,
		arg.UseKnowledgeGraph,
		arg.OrgID,
		arg.FolderID,
		arg.UploadedByID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Text,
		&i.DocumentKey,
		&i.DocumentUrl,
		&i.ProcessingStatus,
		&i.ProcessingDetails,
		&i.Metadata,
		&i.UseKnowledgeGraph,
		&i.OrgID,
		&i.FolderID,
		&i.UploadedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, description, text, document_key, document_url, processing_status, processing_details, metadata, use_knowledge_graph, org_id, folder_id, uploaded_by_id, created_at, updated_at FROM documents WHERE id = $1
`

func (q *Queries) GetDocument(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Text,
		&i.DocumentKey,
		&i.DocumentUrl,
		&i.ProcessingStatus,
		&i.ProcessingDetails,
		&i.Metadata,
		&i.UseKnowledgeGraph,
		&i.OrgID,
		&i.FolderID,
		&i.UploadedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByKey = `-- name: GetDocumentByKey :one
SELECT id, title, description, text, document_key, document_url, processing_status, processing_details, metadata, use_knowledge_graph, org_id, folder_id, uploaded_by_id, created_at, updated_at FROM documents WHERE document_key = $1 AND org_id = $2
`

type GetDocumentByKeyParams struct {
	DocumentKey string      `json:"document_key"`
	OrgID       pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetDocumentByKey(ctx context.Context, arg GetDocumentByKeyParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByKey, arg.DocumentKey, arg.OrgID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Text,
		&i.DocumentKey,
		&i.DocumentUrl,
		&i.ProcessingStatus,
		&i.ProcessingDetails,
		&i.Metadata,
		&i.UseKnowledgeGraph,
		&i.OrgID,
		&i.FolderID,
		&i.UploadedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentTags = `-- name: ListDocumentTags :many

SELECT t.id, t.name, t.org_id, t.created_at, t.updated_at FROM tags t
JOIN document_tags dt ON dt.tag_id = t.id
WHERE dt.document_id = $1
`

// Document Tags
func (q *Queries) ListDocumentTags(ctx context.Context, documentID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listDocumentTags, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, title, description, text, document_key, document_url, processing_status, processing_details, metadata, use_knowledge_graph, org_id, folder_id, uploaded_by_id, created_at, updated_at FROM documents ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Text,
			&i.DocumentKey,
			&i.DocumentUrl,
			&i.ProcessingStatus,
			&i.ProcessingDetails,
			&i.Metadata,
			&i.UseKnowledgeGraph,
			&i.OrgID,
			&i.FolderID,
			&i.UploadedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByFolder = `-- name: ListDocumentsByFolder :many
SELECT id, title, description, text, document_key, document_url, processing_status, processing_details, metadata, use_knowledge_graph, org_id, folder_id, uploaded_by_id, created_at, updated_at FROM documents WHERE folder_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListDocumentsByFolderParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListDocumentsByFolder(ctx context.Context, arg ListDocumentsByFolderParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByFolder, arg.FolderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Text,
			&i.DocumentKey,
			&i.DocumentUrl,
			&i.ProcessingStatus,
			&i.ProcessingDetails,
			&i.Metadata,
			&i.UseKnowledgeGraph,
			&i.OrgID,
			&i.FolderID,
			&i.UploadedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsForFolders = `-- name: ListDocumentsForFolders :many
SELECT id, title, description, text, document_key, document_url, processing_status, processing_details, metadata, use_knowledge_graph, org_id, folder_id, uploaded_by_id, created_at, updated_at FROM documents
WHERE org_id = $1 AND (folder_id = ANY($2::uuid[]) OR (folder_id IS NULL AND $3 = true))
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListDocumentsForFoldersParams struct {
	OrgID   pgtype.UUID   `json:"org_id"`
	Column2 []pgtype.UUID `json:"column_2"`
	Column3 interface{}   `json:"column_3"`
	Limit   int32         `json:"limit"`
	Offset  int32         `json:"offset"`
}

// List documents that belong to any of the given folder IDs (or have NULL folder_id)
func (q *Queries) ListDocumentsForFolders(ctx context.Context, arg ListDocumentsForFoldersParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsForFolders,
		arg.OrgID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Text,
			&i.DocumentKey,
			&i.DocumentUrl,
			&i.ProcessingStatus,
			&i.ProcessingDetails,
			&i.Metadata,
			&i.UseKnowledgeGraph,
			&i.OrgID,
			&i.FolderID,
			&i.UploadedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsForOrg = `-- name: ListDocumentsForOrg :many
SELECT id, title, description, text, document_key, document_url, processing_status, processing_details, metadata, use_knowledge_graph, org_id, folder_id, uploaded_by_id, created_at, updated_at FROM documents WHERE org_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListDocumentsForOrgParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListDocumentsForOrg(ctx context.Context, arg ListDocumentsForOrgParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsForOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Text,
			&i.DocumentKey,
			&i.DocumentUrl,
			&i.ProcessingStatus,
			&i.ProcessingDetails,
			&i.Metadata,
			&i.UseKnowledgeGraph,
			&i.OrgID,
			&i.FolderID,
			&i.UploadedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsWithNullFolder = `-- name: ListDocumentsWithNullFolder :many
SELECT id, title, description, text, document_key, document_url, processing_status, processing_details, metadata, use_knowledge_graph, org_id, folder_id, uploaded_by_id, created_at, updated_at FROM documents WHERE org_id = $1 AND folder_id IS NULL ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListDocumentsWithNullFolderParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListDocumentsWithNullFolder(ctx context.Context, arg ListDocumentsWithNullFolderParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsWithNullFolder, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Text,
			&i.DocumentKey,
			&i.DocumentUrl,
			&i.ProcessingStatus,
			&i.ProcessingDetails,
			&i.Metadata,
			&i.UseKnowledgeGraph,
			&i.OrgID,
			&i.FolderID,
			&i.UploadedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentTag = `-- name: RemoveDocumentTag :exec
DELETE FROM document_tags WHERE document_id = $1 AND tag_id = $2
`

type RemoveDocumentTagParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	TagID      pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveDocumentTag(ctx context.Context, arg RemoveDocumentTagParams) error {
	_, err := q.db.Exec(ctx, removeDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const setDocumentTags = `-- name: SetDocumentTags :exec
DELETE FROM document_tags WHERE document_id = $1
`

// Clear and reset all tags for a document
func (q *Queries) SetDocumentTags(ctx context.Context, documentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setDocumentTags, documentID)
	return err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    text = COALESCE($4, text),
    document_url = COALESCE($5, document_url),
    processing_status = COALESCE($6, processing_status),
    processing_details = COALESCE($7, processing_details),
    metadata = COALESCE($8, metadata),
    use_knowledge_graph = COALESCE($9, use_knowledge_graph),
    folder_id = CASE
        WHEN $10::uuid IS NOT NULL THEN $10::uuid
        WHEN $11::boolean = true THEN NULL
        ELSE folder_id
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, text, document_key, document_url, processing_status, processing_details, metadata, use_knowledge_graph, org_id, folder_id, uploaded_by_id, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID                pgtype.UUID `json:"id"`
	Title             pgtype.Text `json:"title"`
	Description       pgtype.Text `json:"description"`
	Text              pgtype.Text `json:"text"`
	DocumentUrl       pgtype.Text `json:"document_url"`
	ProcessingStatus  pgtype.Text `json:"processing_status"`
	ProcessingDetails []byte      `json:"processing_details"`
	Metadata          []byte      `json:"metadata"`
	UseKnowledgeGraph pgtype.Bool `json:"use_knowledge_graph"`
	FolderID          pgtype.UUID `json:"folder_id"`
	ClearFolder       pgtype.Bool `json:"clear_folder"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Text,
		arg.DocumentUrl,
		arg.ProcessingStatus,
		arg.ProcessingDetails,
		arg.Metadata,
		arg.UseKnowledgeGraph,
		arg.FolderID,
		arg.ClearFolder,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Text,
		&i.DocumentKey,
		&i.DocumentUrl,
		&i.ProcessingStatus,
		&i.ProcessingDetails,
		&i.Metadata,
		&i.UseKnowledgeGraph,
		&i.OrgID,
		&i.FolderID,
		&i.UploadedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE documents SET
    processing_status = $2,
    processing_details = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDocumentStatusParams struct {
	ID                pgtype.UUID `json:"id"`
	ProcessingStatus  pgtype.Text `json:"processing_status"`
	ProcessingDetails []byte      `json:"processing_details"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus, arg.ID, arg.ProcessingStatus, arg.ProcessingDetails)
	return err
}
