// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFolderDescendants = `-- name: CountFolderDescendants :one
SELECT COUNT(*) FROM folders f
WHERE f.dot_path = (SELECT f2.dot_path FROM folders f2 WHERE f2.id = $1)
   OR f.dot_path LIKE (SELECT f2.dot_path FROM folders f2 WHERE f2.id = $1) || '.%'
`

func (q *Queries) CountFolderDescendants(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFolderDescendants, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFolders = `-- name: CountFolders :one
SELECT COUNT(*) FROM folders
`

func (q *Queries) CountFolders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFolders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFoldersForOrg = `-- name: CountFoldersForOrg :one
SELECT COUNT(*) FROM folders WHERE org_id = $1
`

func (q *Queries) CountFoldersForOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFoldersForOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (
    id, name, description, "order", dot_path,
    view_permission_masks, contributor_permission_masks,
    viewer_permissions_config, contributor_permissions_config,
    org_id, parent_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, description, "order", dot_path, view_permission_masks, contributor_permission_masks, viewer_permissions_config, contributor_permissions_config, org_id, parent_id, created_at, updated_at
`

type CreateFolderParams struct {
	ID                           pgtype.UUID `json:"id"`
	Name                         string      `json:"name"`
	Description                  pgtype.Text `json:"description"`
	Order                        pgtype.Int4 `json:"order"`
	DotPath                      pgtype.Text `json:"dot_path"`
	ViewPermissionMasks          []int64     `json:"view_permission_masks"`
	ContributorPermissionMasks   []int64     `json:"contributor_permission_masks"`
	ViewerPermissionsConfig      []byte      `json:"viewer_permissions_config"`
	ContributorPermissionsConfig []byte      `json:"contributor_permissions_config"`
	OrgID                        pgtype.UUID `json:"org_id"`
	ParentID                     pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Order,
		arg.DotPath,
		arg.ViewPermissionMasks,
		arg.ContributorPermissionMasks,
		arg.ViewerPermissionsConfig,
		arg.ContributorPermissionsConfig,
		arg.OrgID,
		arg.ParentID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Order,
		&i.DotPath,
		&i.ViewPermissionMasks,
		&i.ContributorPermissionMasks,
		&i.ViewerPermissionsConfig,
		&i.ContributorPermissionsConfig,
		&i.OrgID,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const getFolder = `-- name: GetFolder :one
SELECT id, name, description, "order", dot_path, view_permission_masks, contributor_permission_masks, viewer_permissions_config, contributor_permissions_config, org_id, parent_id, created_at, updated_at FROM folders WHERE id = $1
`

func (q *Queries) GetFolder(ctx context.Context, id pgtype.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Order,
		&i.DotPath,
		&i.ViewPermissionMasks,
		&i.ContributorPermissionMasks,
		&i.ViewerPermissionsConfig,
		&i.ContributorPermissionsConfig,
		&i.OrgID,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByName = `-- name: GetFolderByName :one
SELECT id, name, description, "order", dot_path, view_permission_masks, contributor_permission_masks, viewer_permissions_config, contributor_permissions_config, org_id, parent_id, created_at, updated_at FROM folders WHERE name = $1 AND org_id = $2 AND parent_id IS NOT DISTINCT FROM $3
`

type GetFolderByNameParams struct {
	Name     string      `json:"name"`
	OrgID    pgtype.UUID `json:"org_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) GetFolderByName(ctx context.Context, arg GetFolderByNameParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByName, arg.Name, arg.OrgID, arg.ParentID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Order,
		&i.DotPath,
		&i.ViewPermissionMasks,
		&i.ContributorPermissionMasks,
		&i.ViewerPermissionsConfig,
		&i.ContributorPermissionsConfig,
		&i.OrgID,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderDescendants = `-- name: GetFolderDescendants :many
SELECT f.id, f.name, f.description, f."order", f.dot_path, f.view_permission_masks, f.contributor_permission_masks, f.viewer_permissions_config, f.contributor_permissions_config, f.org_id, f.parent_id, f.created_at, f.updated_at FROM folders f
WHERE f.dot_path = (SELECT f2.dot_path FROM folders f2 WHERE f2.id = $1)
   OR f.dot_path LIKE (SELECT f2.dot_path FROM folders f2 WHERE f2.id = $1) || '.%'
ORDER BY f.dot_path
`

// Returns the folder and all its descendants (via dot_path prefix match)
func (q *Queries) GetFolderDescendants(ctx context.Context, id pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getFolderDescendants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Order,
			&i.DotPath,
			&i.ViewPermissionMasks,
			&i.ContributorPermissionMasks,
			&i.ViewerPermissionsConfig,
			&i.ContributorPermissionsConfig,
			&i.OrgID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextFolderOrder = `-- name: GetNextFolderOrder :one
SELECT COALESCE(MAX("order"), 0) + 1 FROM folders WHERE org_id = $1 AND parent_id IS NOT DISTINCT FROM $2
`

type GetNextFolderOrderParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) GetNextFolderOrder(ctx context.Context, arg GetNextFolderOrderParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextFolderOrder, arg.OrgID, arg.ParentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listChildFolders = `-- name: ListChildFolders :many
SELECT id, name, description, "order", dot_path, view_permission_masks, contributor_permission_masks, viewer_permissions_config, contributor_permissions_config, org_id, parent_id, created_at, updated_at FROM folders WHERE parent_id = $1 ORDER BY "order", name
`

func (q *Queries) ListChildFolders(ctx context.Context, parentID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listChildFolders, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Order,
			&i.DotPath,
			&i.ViewPermissionMasks,
			&i.ContributorPermissionMasks,
			&i.ViewerPermissionsConfig,
			&i.ContributorPermissionsConfig,
			&i.OrgID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many
SELECT id, name, description, "order", dot_path, view_permission_masks, contributor_permission_masks, viewer_permissions_config, contributor_permissions_config, org_id, parent_id, created_at, updated_at FROM folders ORDER BY dot_path, "order", name LIMIT $1 OFFSET $2
`

type ListFoldersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFolders(ctx context.Context, arg ListFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFolders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Order,
			&i.DotPath,
			&i.ViewPermissionMasks,
			&i.ContributorPermissionMasks,
			&i.ViewerPermissionsConfig,
			&i.ContributorPermissionsConfig,
			&i.OrgID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersForOrg = `-- name: ListFoldersForOrg :many
SELECT id, name, description, "order", dot_path, view_permission_masks, contributor_permission_masks, viewer_permissions_config, contributor_permissions_config, org_id, parent_id, created_at, updated_at FROM folders WHERE org_id = $1 ORDER BY dot_path, "order", name LIMIT $2 OFFSET $3
`

type ListFoldersForOrgParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListFoldersForOrg(ctx context.Context, arg ListFoldersForOrgParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersForOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Order,
			&i.DotPath,
			&i.ViewPermissionMasks,
			&i.ContributorPermissionMasks,
			&i.ViewerPermissionsConfig,
			&i.ContributorPermissionsConfig,
			&i.OrgID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFolders = `-- name: ListRootFolders :many
SELECT id, name, description, "order", dot_path, view_permission_masks, contributor_permission_masks, viewer_permissions_config, contributor_permissions_config, org_id, parent_id, created_at, updated_at FROM folders WHERE org_id = $1 AND parent_id IS NULL ORDER BY "order", name LIMIT $2 OFFSET $3
`

type ListRootFoldersParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListRootFolders(ctx context.Context, arg ListRootFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listRootFolders, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Order,
			&i.DotPath,
			&i.ViewPermissionMasks,
			&i.ContributorPermissionMasks,
			&i.ViewerPermissionsConfig,
			&i.ContributorPermissionsConfig,
			&i.OrgID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderFolders = `-- name: ReorderFolders :exec
UPDATE folders SET "order" = $2, updated_at = NOW() WHERE id = $1
`

type ReorderFoldersParams struct {
	ID    pgtype.UUID `json:"id"`
	Order pgtype.Int4 `json:"order"`
}

// Update the order of folders for drag-and-drop reordering
func (q *Queries) ReorderFolders(ctx context.Context, arg ReorderFoldersParams) error {
	_, err := q.db.Exec(ctx, reorderFolders, arg.ID, arg.Order)
	return err
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    "order" = COALESCE($4, "order"),
    dot_path = COALESCE($5, dot_path),
    view_permission_masks = COALESCE($6, view_permission_masks),
    contributor_permission_masks = COALESCE($7, contributor_permission_masks),
    viewer_permissions_config = COALESCE($8, viewer_permissions_config),
    contributor_permissions_config = COALESCE($9, contributor_permissions_config),
    parent_id = CASE
        WHEN $10::uuid IS NOT NULL THEN $10::uuid
        WHEN $11::boolean = true THEN NULL
        ELSE parent_id
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, "order", dot_path, view_permission_masks, contributor_permission_masks, viewer_permissions_config, contributor_permissions_config, org_id, parent_id, created_at, updated_at
`

type UpdateFolderParams struct {
	ID                           pgtype.UUID `json:"id"`
	Name                         pgtype.Text `json:"name"`
	Description                  pgtype.Text `json:"description"`
	Order                        pgtype.Int4 `json:"order"`
	DotPath                      pgtype.Text `json:"dot_path"`
	ViewPermissionMasks          []int64     `json:"view_permission_masks"`
	ContributorPermissionMasks   []int64     `json:"contributor_permission_masks"`
	ViewerPermissionsConfig      []byte      `json:"viewer_permissions_config"`
	ContributorPermissionsConfig []byte      `json:"contributor_permissions_config"`
	ParentID                     pgtype.UUID `json:"parent_id"`
	ClearParent                  pgtype.Bool `json:"clear_parent"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolder,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Order,
		arg.DotPath,
		arg.ViewPermissionMasks,
		arg.ContributorPermissionMasks,
		arg.ViewerPermissionsConfig,
		arg.ContributorPermissionsConfig,
		arg.ParentID,
		arg.ClearParent,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Order,
		&i.DotPath,
		&i.ViewPermissionMasks,
		&i.ContributorPermissionMasks,
		&i.ViewerPermissionsConfig,
		&i.ContributorPermissionsConfig,
		&i.OrgID,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFolderDotPath = `-- name: UpdateFolderDotPath :exec
UPDATE folders SET
    dot_path = $1::text || SUBSTRING(dot_path FROM $2::int + 1),
    updated_at = NOW()
WHERE dot_path = $3 OR dot_path LIKE $3 || '.%'
`

type UpdateFolderDotPathParams struct {
	NewPrefix    string      `json:"new_prefix"`
	OldPrefixLen int32       `json:"old_prefix_len"`
	OldPrefix    pgtype.Text `json:"old_prefix"`
}

// Update dot_path for a folder and all its descendants when moved
func (q *Queries) UpdateFolderDotPath(ctx context.Context, arg UpdateFolderDotPathParams) error {
	_, err := q.db.Exec(ctx, updateFolderDotPath, arg.NewPrefix, arg.OldPrefixLen, arg.OldPrefix)
	return err
}
