// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMembershipDepartment = `-- name: AddMembershipDepartment :exec
INSERT INTO membership_departments (membership_id, department_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMembershipDepartmentParams struct {
	MembershipID pgtype.UUID `json:"membership_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
}

func (q *Queries) AddMembershipDepartment(ctx context.Context, arg AddMembershipDepartmentParams) error {
	_, err := q.db.Exec(ctx, addMembershipDepartment, arg.MembershipID, arg.DepartmentID)
	return err
}

const addMembershipGroup = `-- name: AddMembershipGroup :exec
INSERT INTO membership_groups (membership_id, group_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMembershipGroupParams struct {
	MembershipID pgtype.UUID `json:"membership_id"`
	GroupID      pgtype.UUID `json:"group_id"`
}

func (q *Queries) AddMembershipGroup(ctx context.Context, arg AddMembershipGroupParams) error {
	_, err := q.db.Exec(ctx, addMembershipGroup, arg.MembershipID, arg.GroupID)
	return err
}

const addMembershipRegion = `-- name: AddMembershipRegion :exec
INSERT INTO membership_regions (membership_id, region_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMembershipRegionParams struct {
	MembershipID pgtype.UUID `json:"membership_id"`
	RegionID     pgtype.UUID `json:"region_id"`
}

func (q *Queries) AddMembershipRegion(ctx context.Context, arg AddMembershipRegionParams) error {
	_, err := q.db.Exec(ctx, addMembershipRegion, arg.MembershipID, arg.RegionID)
	return err
}

const addMembershipRole = `-- name: AddMembershipRole :exec
INSERT INTO membership_roles (membership_id, role_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMembershipRoleParams struct {
	MembershipID pgtype.UUID `json:"membership_id"`
	RoleID       pgtype.UUID `json:"role_id"`
}

func (q *Queries) AddMembershipRole(ctx context.Context, arg AddMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, addMembershipRole, arg.MembershipID, arg.RoleID)
	return err
}

const clearMembershipDepartments = `-- name: ClearMembershipDepartments :exec
DELETE FROM membership_departments WHERE membership_id = $1
`

// Membership departments junction
func (q *Queries) ClearMembershipDepartments(ctx context.Context, membershipID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearMembershipDepartments, membershipID)
	return err
}

const clearMembershipGroups = `-- name: ClearMembershipGroups :exec
DELETE FROM membership_groups WHERE membership_id = $1
`

// Membership groups junction
func (q *Queries) ClearMembershipGroups(ctx context.Context, membershipID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearMembershipGroups, membershipID)
	return err
}

const clearMembershipRegions = `-- name: ClearMembershipRegions :exec
DELETE FROM membership_regions WHERE membership_id = $1
`

// Membership regions junction
func (q *Queries) ClearMembershipRegions(ctx context.Context, membershipID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearMembershipRegions, membershipID)
	return err
}

const clearMembershipRoles = `-- name: ClearMembershipRoles :exec
DELETE FROM membership_roles WHERE membership_id = $1
`

// Membership roles junction
func (q *Queries) ClearMembershipRoles(ctx context.Context, membershipID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearMembershipRoles, membershipID)
	return err
}

const countMembershipsInOrg = `-- name: CountMembershipsInOrg :one
SELECT COUNT(*) FROM user_org_memberships WHERE org_id = $1
`

func (q *Queries) CountMembershipsInOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsInOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO user_org_memberships (id, profile_id, org_id, is_org_admin)
VALUES ($1, $2, $3, $4)
RETURNING id, profile_id, org_id, is_org_admin, created_at, updated_at
`

type CreateMembershipParams struct {
	ID         pgtype.UUID `json:"id"`
	ProfileID  pgtype.UUID `json:"profile_id"`
	OrgID      pgtype.UUID `json:"org_id"`
	IsOrgAdmin pgtype.Bool `json:"is_org_admin"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (UserOrgMembership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.ID,
		arg.ProfileID,
		arg.OrgID,
		arg.IsOrgAdmin,
	)
	var i UserOrgMembership
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.OrgID,
		&i.IsOrgAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM user_org_memberships WHERE id = $1
`

func (q *Queries) DeleteMembership(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMembership, id)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, profile_id, org_id, is_org_admin, created_at, updated_at FROM user_org_memberships WHERE id = $1
`

func (q *Queries) GetMembership(ctx context.Context, id pgtype.UUID) (UserOrgMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, id)
	var i UserOrgMembership
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.OrgID,
		&i.IsOrgAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipByUserAndOrg = `-- name: GetMembershipByUserAndOrg :one
SELECT id, profile_id, org_id, is_org_admin, created_at, updated_at FROM user_org_memberships
WHERE profile_id = $1 AND org_id = $2
`

type GetMembershipByUserAndOrgParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	OrgID     pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetMembershipByUserAndOrg(ctx context.Context, arg GetMembershipByUserAndOrgParams) (UserOrgMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserAndOrg, arg.ProfileID, arg.OrgID)
	var i UserOrgMembership
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.OrgID,
		&i.IsOrgAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembershipDepartments = `-- name: ListMembershipDepartments :many
SELECT d.id, d.name, d.description, d.permission_number, d.org_id, d.created_at, d.updated_at FROM departments d
JOIN membership_departments md ON md.department_id = d.id
WHERE md.membership_id = $1
`

func (q *Queries) ListMembershipDepartments(ctx context.Context, membershipID pgtype.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listMembershipDepartments, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PermissionNumber,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipGroups = `-- name: ListMembershipGroups :many
SELECT g.id, g.name, g.description, g.permission_number, g.org_id, g.created_at, g.updated_at FROM groups g
JOIN membership_groups mg ON mg.group_id = g.id
WHERE mg.membership_id = $1
`

func (q *Queries) ListMembershipGroups(ctx context.Context, membershipID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listMembershipGroups, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PermissionNumber,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipRegions = `-- name: ListMembershipRegions :many
SELECT r.id, r.name, r.description, r.permission_number, r.org_id, r.created_at, r.updated_at FROM regions r
JOIN membership_regions mr ON mr.region_id = r.id
WHERE mr.membership_id = $1
`

func (q *Queries) ListMembershipRegions(ctx context.Context, membershipID pgtype.UUID) ([]Region, error) {
	rows, err := q.db.Query(ctx, listMembershipRegions, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PermissionNumber,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipRoles = `-- name: ListMembershipRoles :many
SELECT r.id, r.name, r.description, r.permission_number, r.org_id, r.created_at, r.updated_at FROM roles r
JOIN membership_roles mr ON mr.role_id = r.id
WHERE mr.membership_id = $1
`

func (q *Queries) ListMembershipRoles(ctx context.Context, membershipID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listMembershipRoles, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PermissionNumber,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsInOrg = `-- name: ListMembershipsInOrg :many
SELECT id, profile_id, org_id, is_org_admin, created_at, updated_at FROM user_org_memberships
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMembershipsInOrgParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListMembershipsInOrg(ctx context.Context, arg ListMembershipsInOrgParams) ([]UserOrgMembership, error) {
	rows, err := q.db.Query(ctx, listMembershipsInOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserOrgMembership
	for rows.Next() {
		var i UserOrgMembership
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.OrgID,
			&i.IsOrgAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembership = `-- name: UpdateMembership :one
UPDATE user_org_memberships SET
    is_org_admin = COALESCE($2, is_org_admin),
    updated_at = NOW()
WHERE id = $1
RETURNING id, profile_id, org_id, is_org_admin, created_at, updated_at
`

type UpdateMembershipParams struct {
	ID         pgtype.UUID `json:"id"`
	IsOrgAdmin pgtype.Bool `json:"is_org_admin"`
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (UserOrgMembership, error) {
	row := q.db.QueryRow(ctx, updateMembership, arg.ID, arg.IsOrgAdmin)
	var i UserOrgMembership
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.OrgID,
		&i.IsOrgAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMembership = `-- name: UpsertMembership :one
INSERT INTO user_org_memberships (id, profile_id, org_id, is_org_admin)
VALUES ($1, $2, $3, $4)
ON CONFLICT (profile_id, org_id) DO UPDATE SET
    is_org_admin = EXCLUDED.is_org_admin,
    updated_at = NOW()
RETURNING id, profile_id, org_id, is_org_admin, created_at, updated_at
`

type UpsertMembershipParams struct {
	ID         pgtype.UUID `json:"id"`
	ProfileID  pgtype.UUID `json:"profile_id"`
	OrgID      pgtype.UUID `json:"org_id"`
	IsOrgAdmin pgtype.Bool `json:"is_org_admin"`
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (UserOrgMembership, error) {
	row := q.db.QueryRow(ctx, upsertMembership,
		arg.ID,
		arg.ProfileID,
		arg.OrgID,
		arg.IsOrgAdmin,
	)
	var i UserOrgMembership
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.OrgID,
		&i.IsOrgAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
