// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatSession struct {
	ID        pgtype.UUID        `json:"id"`
	ChatData  []byte             `json:"chat_data"`
	Deleted   pgtype.Bool        `json:"deleted"`
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Department struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	PermissionNumber pgtype.Int2        `json:"permission_number"`
	OrgID            pgtype.UUID        `json:"org_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Document struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Text              pgtype.Text        `json:"text"`
	DocumentKey       string             `json:"document_key"`
	DocumentUrl       pgtype.Text        `json:"document_url"`
	ProcessingStatus  pgtype.Text        `json:"processing_status"`
	ProcessingDetails []byte             `json:"processing_details"`
	Metadata          []byte             `json:"metadata"`
	UseKnowledgeGraph pgtype.Bool        `json:"use_knowledge_graph"`
	OrgID             pgtype.UUID        `json:"org_id"`
	FolderID          pgtype.UUID        `json:"folder_id"`
	UploadedByID      pgtype.UUID        `json:"uploaded_by_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DocumentAccess struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	FolderID  pgtype.UUID        `json:"folder_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DocumentAttributeDefinition struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	AttributeType   pgtype.Text        `json:"attribute_type"`
	PicklistOptions []byte             `json:"picklist_options"`
	Required        pgtype.Bool        `json:"required"`
	Order           pgtype.Int4        `json:"order"`
	OrgID           pgtype.UUID        `json:"org_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DocumentTag struct {
	DocumentID pgtype.UUID `json:"document_id"`
	TagID      pgtype.UUID `json:"tag_id"`
}

type Folder struct {
	ID                           pgtype.UUID        `json:"id"`
	Name                         string             `json:"name"`
	Description                  pgtype.Text        `json:"description"`
	Order                        pgtype.Int4        `json:"order"`
	DotPath                      pgtype.Text        `json:"dot_path"`
	ViewPermissionMasks          []int64            `json:"view_permission_masks"`
	ContributorPermissionMasks   []int64            `json:"contributor_permission_masks"`
	ViewerPermissionsConfig      []byte             `json:"viewer_permissions_config"`
	ContributorPermissionsConfig []byte             `json:"contributor_permissions_config"`
	OrgID                        pgtype.UUID        `json:"org_id"`
	ParentID                     pgtype.UUID        `json:"parent_id"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	PermissionNumber pgtype.Int2        `json:"permission_number"`
	OrgID            pgtype.UUID        `json:"org_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MembershipDepartment struct {
	MembershipID pgtype.UUID `json:"membership_id"`
	DepartmentID pgtype.UUID `json:"department_id"`
}

type MembershipGroup struct {
	MembershipID pgtype.UUID `json:"membership_id"`
	GroupID      pgtype.UUID `json:"group_id"`
}

type MembershipRegion struct {
	MembershipID pgtype.UUID `json:"membership_id"`
	RegionID     pgtype.UUID `json:"region_id"`
}

type MembershipRole struct {
	MembershipID pgtype.UUID `json:"membership_id"`
	RoleID       pgtype.UUID `json:"role_id"`
}

type Org struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	UseKnowledgeGraph pgtype.Bool        `json:"use_knowledge_graph"`
	OpenaiApiKey      pgtype.Text        `json:"openai_api_key"`
	PermissionNumber  pgtype.Int2        `json:"permission_number"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Region struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	PermissionNumber pgtype.Int2        `json:"permission_number"`
	OrgID            pgtype.UUID        `json:"org_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	PermissionNumber pgtype.Int2        `json:"permission_number"`
	OrgID            pgtype.UUID        `json:"org_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OrgID     pgtype.UUID        `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserOrgMembership struct {
	ID         pgtype.UUID        `json:"id"`
	ProfileID  pgtype.UUID        `json:"profile_id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	IsOrgAdmin pgtype.Bool        `json:"is_org_admin"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type UserProfile struct {
	ID          pgtype.UUID        `json:"id"`
	KeycloakSub string             `json:"keycloak_sub"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Description pgtype.Text        `json:"description"`
	IsSiteAdmin pgtype.Bool        `json:"is_site_admin"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
