// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllOrgs = `-- name: CountAllOrgs :one
SELECT COUNT(*) FROM orgs
`

func (q *Queries) CountAllOrgs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllOrgs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrgsForUser = `-- name: CountOrgsForUser :one
SELECT COUNT(*) FROM orgs o
JOIN user_org_memberships m ON m.org_id = o.id
WHERE m.profile_id = $1
`

func (q *Queries) CountOrgsForUser(ctx context.Context, profileID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgsForUser, profileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (id, name, description, use_knowledge_graph, permission_number)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, use_knowledge_graph, openai_api_key, permission_number, created_at, updated_at
`

type CreateOrgParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	Description       pgtype.Text `json:"description"`
	UseKnowledgeGraph pgtype.Bool `json:"use_knowledge_graph"`
	PermissionNumber  pgtype.Int2 `json:"permission_number"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UseKnowledgeGraph,
		arg.PermissionNumber,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UseKnowledgeGraph,
		&i.OpenaiApiKey,
		&i.PermissionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrg = `-- name: DeleteOrg :exec
DELETE FROM orgs WHERE id = $1
`

func (q *Queries) DeleteOrg(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrg, id)
	return err
}

const getNextOrgPermissionNumber = `-- name: GetNextOrgPermissionNumber :one
SELECT COALESCE(MAX(permission_number), 0) + 1 FROM orgs FOR UPDATE
`

func (q *Queries) GetNextOrgPermissionNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextOrgPermissionNumber)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, description, use_knowledge_graph, openai_api_key, permission_number, created_at, updated_at FROM orgs WHERE id = $1
`

func (q *Queries) GetOrg(ctx context.Context, id pgtype.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UseKnowledgeGraph,
		&i.OpenaiApiKey,
		&i.PermissionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isUserMemberOfOrg = `-- name: IsUserMemberOfOrg :one
SELECT EXISTS(
    SELECT 1 FROM user_org_memberships
    WHERE profile_id = $1 AND org_id = $2
) AS is_member
`

type IsUserMemberOfOrgParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	OrgID     pgtype.UUID `json:"org_id"`
}

func (q *Queries) IsUserMemberOfOrg(ctx context.Context, arg IsUserMemberOfOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserMemberOfOrg, arg.ProfileID, arg.OrgID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listAllOrgs = `-- name: ListAllOrgs :many
SELECT id, name, description, use_knowledge_graph, openai_api_key, permission_number, created_at, updated_at FROM orgs ORDER BY name LIMIT $1 OFFSET $2
`

type ListAllOrgsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllOrgs(ctx context.Context, arg ListAllOrgsParams) ([]Org, error) {
	rows, err := q.db.Query(ctx, listAllOrgs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UseKnowledgeGraph,
			&i.OpenaiApiKey,
			&i.PermissionNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT o.id, o.name, o.description, o.use_knowledge_graph, o.openai_api_key, o.permission_number, o.created_at, o.updated_at FROM orgs o
JOIN user_org_memberships m ON m.org_id = o.id
WHERE m.profile_id = $1
ORDER BY o.name
LIMIT $2 OFFSET $3
`

type ListOrgsForUserParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListOrgsForUser(ctx context.Context, arg ListOrgsForUserParams) ([]Org, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, arg.ProfileID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Org
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UseKnowledgeGraph,
			&i.OpenaiApiKey,
			&i.PermissionNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE orgs SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    use_knowledge_graph = COALESCE($4, use_knowledge_graph),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, use_knowledge_graph, openai_api_key, permission_number, created_at, updated_at
`

type UpdateOrgParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              pgtype.Text `json:"name"`
	Description       pgtype.Text `json:"description"`
	UseKnowledgeGraph pgtype.Bool `json:"use_knowledge_graph"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UseKnowledgeGraph,
	)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UseKnowledgeGraph,
		&i.OpenaiApiKey,
		&i.PermissionNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
