// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMembershipDepartment(ctx context.Context, arg AddMembershipDepartmentParams) error
	AddMembershipGroup(ctx context.Context, arg AddMembershipGroupParams) error
	AddMembershipRegion(ctx context.Context, arg AddMembershipRegionParams) error
	AddMembershipRole(ctx context.Context, arg AddMembershipRoleParams) error
	// Membership departments junction
	ClearMembershipDepartments(ctx context.Context, membershipID pgtype.UUID) error
	// Membership groups junction
	ClearMembershipGroups(ctx context.Context, membershipID pgtype.UUID) error
	// Membership regions junction
	ClearMembershipRegions(ctx context.Context, membershipID pgtype.UUID) error
	// Membership roles junction
	ClearMembershipRoles(ctx context.Context, membershipID pgtype.UUID) error
	CountAllOrgs(ctx context.Context) (int64, error)
	CountDepartments(ctx context.Context) (int64, error)
	CountGroups(ctx context.Context) (int64, error)
	CountMembershipsInOrg(ctx context.Context, orgID pgtype.UUID) (int64, error)
	CountOrgsForUser(ctx context.Context, profileID pgtype.UUID) (int64, error)
	CountRegions(ctx context.Context) (int64, error)
	CountRoles(ctx context.Context) (int64, error)
	CountUsersInOrg(ctx context.Context, orgID pgtype.UUID) (int64, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (UserOrgMembership, error)
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error)
	CreateRegion(ctx context.Context, arg CreateRegionParams) (Region, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	DeleteDepartment(ctx context.Context, id pgtype.UUID) error
	DeleteGroup(ctx context.Context, id pgtype.UUID) error
	DeleteMembership(ctx context.Context, id pgtype.UUID) error
	DeleteOrg(ctx context.Context, id pgtype.UUID) error
	DeleteRegion(ctx context.Context, id pgtype.UUID) error
	DeleteRole(ctx context.Context, id pgtype.UUID) error
	// Departments
	GetDepartment(ctx context.Context, id pgtype.UUID) (Department, error)
	// Groups
	GetGroup(ctx context.Context, id pgtype.UUID) (Group, error)
	GetMembership(ctx context.Context, id pgtype.UUID) (UserOrgMembership, error)
	GetMembershipByUserAndOrg(ctx context.Context, arg GetMembershipByUserAndOrgParams) (UserOrgMembership, error)
	GetNextDepartmentPermissionNumber(ctx context.Context) (int32, error)
	GetNextGroupPermissionNumber(ctx context.Context) (int32, error)
	GetNextOrgPermissionNumber(ctx context.Context) (int32, error)
	GetNextRegionPermissionNumber(ctx context.Context) (int32, error)
	GetNextRolePermissionNumber(ctx context.Context) (int32, error)
	GetOrg(ctx context.Context, id pgtype.UUID) (Org, error)
	// Regions
	GetRegion(ctx context.Context, id pgtype.UUID) (Region, error)
	// Roles
	GetRole(ctx context.Context, id pgtype.UUID) (Role, error)
	GetUserProfile(ctx context.Context, id pgtype.UUID) (UserProfile, error)
	GetUserProfileByEmail(ctx context.Context, email string) (UserProfile, error)
	GetUserProfileByKeycloakSub(ctx context.Context, keycloakSub string) (UserProfile, error)
	IsUserMemberOfOrg(ctx context.Context, arg IsUserMemberOfOrgParams) (bool, error)
	ListAllOrgs(ctx context.Context, arg ListAllOrgsParams) ([]Org, error)
	ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]Department, error)
	ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error)
	ListMembershipDepartments(ctx context.Context, membershipID pgtype.UUID) ([]Department, error)
	ListMembershipGroups(ctx context.Context, membershipID pgtype.UUID) ([]Group, error)
	ListMembershipRegions(ctx context.Context, membershipID pgtype.UUID) ([]Region, error)
	ListMembershipRoles(ctx context.Context, membershipID pgtype.UUID) ([]Role, error)
	ListMembershipsInOrg(ctx context.Context, arg ListMembershipsInOrgParams) ([]UserOrgMembership, error)
	ListOrgsForUser(ctx context.Context, arg ListOrgsForUserParams) ([]Org, error)
	ListRegions(ctx context.Context, arg ListRegionsParams) ([]Region, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	ListUsersInOrg(ctx context.Context, arg ListUsersInOrgParams) ([]UserProfile, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateMembership(ctx context.Context, arg UpdateMembershipParams) (UserOrgMembership, error)
	UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error)
	UpdateRegion(ctx context.Context, arg UpdateRegionParams) (Region, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
	UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (UserOrgMembership, error)
	UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
