// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTags = `-- name: CountTags :one
SELECT COUNT(*) FROM tags
`

func (q *Queries) CountTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTagsForOrg = `-- name: CountTagsForOrg :one
SELECT COUNT(*) FROM tags WHERE org_id = $1
`

func (q *Queries) CountTagsForOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTagsForOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, name, org_id)
VALUES ($1, $2, $3)
RETURNING id, name, org_id, created_at, updated_at
`

type CreateTagParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.ID, arg.Name, arg.OrgID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, org_id, created_at, updated_at FROM tags WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, org_id, created_at, updated_at FROM tags WHERE name = $1 AND org_id = $2
`

type GetTagByNameParams struct {
	Name  string      `json:"name"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, arg.Name, arg.OrgID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagsByIDs = `-- name: GetTagsByIDs :many
SELECT id, name, org_id, created_at, updated_at FROM tags WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetTagsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTagsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, org_id, created_at, updated_at FROM tags ORDER BY name LIMIT $1 OFFSET $2
`

type ListTagsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForDocument = `-- name: ListTagsForDocument :many
SELECT t.id, t.name, t.org_id, t.created_at, t.updated_at FROM tags t
JOIN document_tags dt ON dt.tag_id = t.id
WHERE dt.document_id = $1
ORDER BY t.name
`

func (q *Queries) ListTagsForDocument(ctx context.Context, documentID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsForDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForOrg = `-- name: ListTagsForOrg :many
SELECT id, name, org_id, created_at, updated_at FROM tags WHERE org_id = $1 ORDER BY name LIMIT $2 OFFSET $3
`

type ListTagsForOrgParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListTagsForOrg(ctx context.Context, arg ListTagsForOrgParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsForOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET
    name = COALESCE($2, name),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, org_id, created_at, updated_at
`

type UpdateTagParams struct {
	ID   pgtype.UUID `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
