// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersInOrg = `-- name: CountUsersInOrg :one
SELECT COUNT(*) FROM user_profiles up
JOIN user_org_memberships m ON m.profile_id = up.id
WHERE m.org_id = $1
`

func (q *Queries) CountUsersInOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersInOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (id, auth_subject, username, email, description, is_site_admin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, auth_subject, username, email, description, is_site_admin, created_at, updated_at
`

type CreateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	AuthSubject string      `json:"auth_subject"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	Description pgtype.Text `json:"description"`
	IsSiteAdmin pgtype.Bool `json:"is_site_admin"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.ID,
		arg.AuthSubject,
		arg.Username,
		arg.Email,
		arg.Description,
		arg.IsSiteAdmin,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, auth_subject, username, email, description, is_site_admin, created_at, updated_at FROM user_profiles WHERE id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, id pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByAuthSubject = `-- name: GetUserProfileByAuthSubject :one
SELECT id, auth_subject, username, email, description, is_site_admin, created_at, updated_at FROM user_profiles WHERE auth_subject = $1
`

func (q *Queries) GetUserProfileByAuthSubject(ctx context.Context, authSubject string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByAuthSubject, authSubject)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByEmailCI = `-- name: GetUserProfileByEmailCI :one
SELECT id, auth_subject, username, email, description, is_site_admin, created_at, updated_at FROM user_profiles WHERE LOWER(email) = LOWER($1)
`

// Case-insensitive email lookup for the verified-email relink: Keycloak-stored
// emails and Clerk-supplied emails can differ only by case, and an exact match
// would miss → fresh provision → email UNIQUE violation (lockout). Email is
// UNIQUE so at most one row matches in practice.
func (q *Queries) GetUserProfileByEmailCI(ctx context.Context, lower string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByEmailCI, lower)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersInOrg = `-- name: ListUsersInOrg :many
SELECT up.id, up.auth_subject, up.username, up.email, up.description, up.is_site_admin, up.created_at, up.updated_at FROM user_profiles up
JOIN user_org_memberships m ON m.profile_id = up.id
WHERE m.org_id = $1
ORDER BY up.username
LIMIT $2 OFFSET $3
`

type ListUsersInOrgParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUsersInOrg(ctx context.Context, arg ListUsersInOrgParams) ([]UserProfile, error) {
	rows, err := q.db.Query(ctx, listUsersInOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProfile
	for rows.Next() {
		var i UserProfile
		if err := rows.Scan(
			&i.ID,
			&i.AuthSubject,
			&i.Username,
			&i.Email,
			&i.Description,
			&i.IsSiteAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relinkAuthSubject = `-- name: RelinkAuthSubject :one
UPDATE user_profiles SET
    auth_subject = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, auth_subject, username, email, description, is_site_admin, created_at, updated_at
`

type RelinkAuthSubjectParams struct {
	ID          pgtype.UUID `json:"id"`
	AuthSubject string      `json:"auth_subject"`
}

// Rebind an existing profile's auth_subject to a new IdP subject (verified-email
// relink on first Clerk login). Keys on the internal id, so memberships and the
// access_mask are preserved. ONLY auth_subject changes — username/email are
// left untouched to avoid colliding with their UNIQUE constraints.
func (q *Queries) RelinkAuthSubject(ctx context.Context, arg RelinkAuthSubjectParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, relinkAuthSubject, arg.ID, arg.AuthSubject)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles SET
    username = COALESCE($2, username),
    email = COALESCE($3, email),
    description = COALESCE($4, description),
    is_site_admin = COALESCE($5, is_site_admin),
    updated_at = NOW()
WHERE id = $1
RETURNING id, auth_subject, username, email, description, is_site_admin, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	Username    pgtype.Text `json:"username"`
	Email       pgtype.Text `json:"email"`
	Description pgtype.Text `json:"description"`
	IsSiteAdmin pgtype.Bool `json:"is_site_admin"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Description,
		arg.IsSiteAdmin,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (id, auth_subject, username, email, description, is_site_admin)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (auth_subject) DO UPDATE SET
    username = EXCLUDED.username,
    email = EXCLUDED.email,
    updated_at = NOW()
RETURNING id, auth_subject, username, email, description, is_site_admin, created_at, updated_at
`

type UpsertUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	AuthSubject string      `json:"auth_subject"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	Description pgtype.Text `json:"description"`
	IsSiteAdmin pgtype.Bool `json:"is_site_admin"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.ID,
		arg.AuthSubject,
		arg.Username,
		arg.Email,
		arg.Description,
		arg.IsSiteAdmin,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AuthSubject,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
