// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersInOrg = `-- name: CountUsersInOrg :one
SELECT COUNT(*) FROM user_profiles up
JOIN user_org_memberships m ON m.profile_id = up.id
WHERE m.org_id = $1
`

func (q *Queries) CountUsersInOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersInOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (id, keycloak_sub, username, email, description, is_site_admin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, keycloak_sub, username, email, description, is_site_admin, created_at, updated_at
`

type CreateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	KeycloakSub string      `json:"keycloak_sub"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	Description pgtype.Text `json:"description"`
	IsSiteAdmin pgtype.Bool `json:"is_site_admin"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.ID,
		arg.KeycloakSub,
		arg.Username,
		arg.Email,
		arg.Description,
		arg.IsSiteAdmin,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.KeycloakSub,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, keycloak_sub, username, email, description, is_site_admin, created_at, updated_at FROM user_profiles WHERE id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, id pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.KeycloakSub,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByEmail = `-- name: GetUserProfileByEmail :one
SELECT id, keycloak_sub, username, email, description, is_site_admin, created_at, updated_at FROM user_profiles WHERE email = $1
`

func (q *Queries) GetUserProfileByEmail(ctx context.Context, email string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByEmail, email)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.KeycloakSub,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileByKeycloakSub = `-- name: GetUserProfileByKeycloakSub :one
SELECT id, keycloak_sub, username, email, description, is_site_admin, created_at, updated_at FROM user_profiles WHERE keycloak_sub = $1
`

func (q *Queries) GetUserProfileByKeycloakSub(ctx context.Context, keycloakSub string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByKeycloakSub, keycloakSub)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.KeycloakSub,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersInOrg = `-- name: ListUsersInOrg :many
SELECT up.id, up.keycloak_sub, up.username, up.email, up.description, up.is_site_admin, up.created_at, up.updated_at FROM user_profiles up
JOIN user_org_memberships m ON m.profile_id = up.id
WHERE m.org_id = $1
ORDER BY up.username
LIMIT $2 OFFSET $3
`

type ListUsersInOrgParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUsersInOrg(ctx context.Context, arg ListUsersInOrgParams) ([]UserProfile, error) {
	rows, err := q.db.Query(ctx, listUsersInOrg, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserProfile
	for rows.Next() {
		var i UserProfile
		if err := rows.Scan(
			&i.ID,
			&i.KeycloakSub,
			&i.Username,
			&i.Email,
			&i.Description,
			&i.IsSiteAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles SET
    username = COALESCE($2, username),
    email = COALESCE($3, email),
    description = COALESCE($4, description),
    is_site_admin = COALESCE($5, is_site_admin),
    updated_at = NOW()
WHERE id = $1
RETURNING id, keycloak_sub, username, email, description, is_site_admin, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	Username    pgtype.Text `json:"username"`
	Email       pgtype.Text `json:"email"`
	Description pgtype.Text `json:"description"`
	IsSiteAdmin pgtype.Bool `json:"is_site_admin"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Description,
		arg.IsSiteAdmin,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.KeycloakSub,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (id, keycloak_sub, username, email, description, is_site_admin)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (keycloak_sub) DO UPDATE SET
    username = EXCLUDED.username,
    email = EXCLUDED.email,
    updated_at = NOW()
RETURNING id, keycloak_sub, username, email, description, is_site_admin, created_at, updated_at
`

type UpsertUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	KeycloakSub string      `json:"keycloak_sub"`
	Username    string      `json:"username"`
	Email       string      `json:"email"`
	Description pgtype.Text `json:"description"`
	IsSiteAdmin pgtype.Bool `json:"is_site_admin"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.ID,
		arg.KeycloakSub,
		arg.Username,
		arg.Email,
		arg.Description,
		arg.IsSiteAdmin,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.KeycloakSub,
		&i.Username,
		&i.Email,
		&i.Description,
		&i.IsSiteAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
