/**
 * Parsing + grading for `puzzle_pad` specs.
 *
 * A spec is author-supplied JSON (typed by hand, generated by an LLM, or stored
 * on a record), so nothing here trusts its shape. Every parser normalises loose
 * input — a bare string where an object was expected, a missing optional, a
 * number where a string belongs — and returns a typed spec or a plain-language
 * reason it cannot be drawn. A pad that cannot be drawn says so; it never
 * renders half a puzzle that no one can finish.
 *
 * Grading lives here too (pure functions over spec + arrangement) so the rules
 * are testable without mounting a component. Note the asymmetry, which is
 * deliberate and documented on the element schema: `choices` and `keypad` are
 * NOT graded here — their answer never reaches the browser — while the other
 * kinds must be sent their target in order to be drawn at all, so the pad grades
 * them locally.
 */

export type PuzzleKind = "choices" | "keypad" | "sequence" | "wires" | "sort" | "color";

export const PUZZLE_KINDS: readonly PuzzleKind[] = [
  "choices",
  "keypad",
  "sequence",
  "wires",
  "sort",
  "color",
] as const;

export function isPuzzleKind(v: unknown): v is PuzzleKind {
  return typeof v === "string" && (PUZZLE_KINDS as readonly string[]).includes(v);
}

export interface ChoiceOption {
  value: string;
  label: string;
}
export interface ChoicesSpec {
  kind: "choices";
  options: ChoiceOption[];
  columns: number;
}

export interface KeypadSpec {
  kind: "keypad";
  maxLen: number;
  units: string | null;
  allowDecimal: boolean;
  allowSign: boolean;
}

export interface SequenceSpec {
  kind: "sequence";
  items: string[];
  /** Item indices in the order they must be tapped. */
  order: number[];
}

export interface WirePair {
  left: string;
  right: string;
  color: string;
}
export interface WiresSpec {
  kind: "wires";
  pairs: WirePair[];
}

export interface SortItem {
  label: string;
  bin: number;
}
export interface SortSpec {
  kind: "sort";
  bins: string[];
  items: SortItem[];
}

export interface PaletteEntry {
  name: string;
  color: string;
}
export interface ColorRegion {
  label: string;
  /** Index into `palette`; -1 in free-paint mode (any colour counts). */
  target: number;
}
export interface ColorSpec {
  kind: "color";
  palette: PaletteEntry[];
  regions: ColorRegion[];
  /** Free paint: any fully-coloured picture counts as done. */
  free: boolean;
}

export type PuzzleSpec = ChoicesSpec | KeypadSpec | SequenceSpec | WiresSpec | SortSpec | ColorSpec;

export type ParseResult = { ok: true; spec: PuzzleSpec } | { ok: false; error: string };

/** `{token}` placeholders in a spec — the same convention as an image url or a
 * link href elsewhere in the schema. Restricted to the shape of a field slug so
 * ordinary text in a puzzle (`{1}`, `{Red}`) is never mistaken for one; the
 * server-side validator uses the identical pattern. */
const SPEC_TOKEN_RE = /\{([a-z][a-z0-9_]*)\}/g;

/**
 * Fill `{field_slug}` placeholders in a spec from the enclosing record's values.
 *
 * This is what lets ONE authored pad serve many records: a view can carry a
 * single spec whose labels read `{choice_a}`…`{choice_d}` and it becomes a
 * different puzzle for every record it renders against, with nothing stored
 * per-record. Substitution happens on the JSON TEXT before parsing, so values
 * are escaped for a JSON string context — a label containing a quote or a
 * backslash must not be able to break out and rewrite the spec's structure.
 *
 * Structural JSON (`{"options": …`) never matches: the pattern requires
 * `{word}` with no quote, which is exactly what a placeholder looks like and
 * what a JSON key does not. An unknown token becomes empty, matching how
 * `{token}` behaves in hrefs.
 */
export function fillSpecTokens(json: string, values: Record<string, unknown>): string {
  if (!json.includes("{")) return json;
  return json.replace(SPEC_TOKEN_RE, (_match, key: string) => {
    const v = values[key];
    if (v == null) return "";
    // Escape via JSON.stringify, then drop its surrounding quotes: the token
    // already sits inside a quoted string in the spec.
    return JSON.stringify(String(v)).slice(1, -1);
  });
}

/** Default wire colours, used when an author doesn't name one. Chosen to stay
 * distinguishable for the most common form of colour blindness (deuteranopia) —
 * a wire puzzle where two leads look identical is unsolvable, not merely ugly. */
const WIRE_COLORS = ["#ef4444", "#3b82f6", "#eab308", "#22c55e", "#a855f7", "#f97316"];

const MAX_ITEMS = 24; // a pad is a handful of things; past this it stops being tappable

function asObject(raw: unknown): Record<string, unknown> | null {
  if (typeof raw === "string") {
    const text = raw.trim();
    if (!text) return null;
    try {
      const parsed: unknown = JSON.parse(text);
      return parsed && typeof parsed === "object" && !Array.isArray(parsed)
        ? (parsed as Record<string, unknown>)
        : null;
    } catch {
      return null;
    }
  }
  if (raw && typeof raw === "object" && !Array.isArray(raw)) return raw as Record<string, unknown>;
  return null;
}

function asArray(v: unknown): unknown[] {
  return Array.isArray(v) ? v : [];
}

/** A displayable label from a loose entry: `"Ignition"` and `{label: "Ignition"}`
 * are both reasonable things for an author to write, so both are accepted. */
function labelOf(entry: unknown, ...keys: string[]): string {
  if (typeof entry === "string") return entry.trim();
  if (typeof entry === "number") return String(entry);
  if (entry && typeof entry === "object") {
    const rec = entry as Record<string, unknown>;
    for (const key of [...keys, "label", "text", "name", "title"]) {
      const v = rec[key];
      if (typeof v === "string" && v.trim()) return v.trim();
      if (typeof v === "number") return String(v);
    }
  }
  return "";
}

function intOf(v: unknown, fallback: number): number {
  const n = typeof v === "string" ? Number(v.trim()) : typeof v === "number" ? v : NaN;
  return Number.isFinite(n) ? Math.trunc(n) : fallback;
}

function boolOf(v: unknown, fallback: boolean): boolean {
  if (typeof v === "boolean") return v;
  if (typeof v === "string") return ["true", "yes", "1"].includes(v.trim().toLowerCase());
  return fallback;
}

/**
 * Turn author JSON into a spec the matching pad can draw.
 *
 * `kind` is passed separately because it may come from a different source than
 * the spec (an element attribute, or its own record field); a `kind` inside the
 * spec is ignored so the two can never disagree about which pad renders.
 */
export function parsePuzzleSpec(kind: PuzzleKind, raw: unknown): ParseResult {
  const obj = asObject(raw) ?? {};
  switch (kind) {
    case "choices":
      return parseChoices(obj);
    case "keypad":
      return parseKeypad(obj);
    case "sequence":
      return parseSequence(obj);
    case "wires":
      return parseWires(obj);
    case "sort":
      return parseSort(obj);
    case "color":
      return parseColor(obj);
    default:
      return { ok: false, error: `Unknown puzzle kind ${String(kind)}.` };
  }
}

/** Label keys an author may write. An entry carrying one of these is making a
 * claim about its own text, which matters when the text is a `{token}`. */
const LABEL_KEYS = ["label", "text", "name", "title"] as const;

function parseChoices(obj: Record<string, unknown>): ParseResult {
  const options: ChoiceOption[] = [];
  for (const entry of asArray(obj.options).slice(0, MAX_ITEMS)) {
    const label = labelOf(entry, "label");
    // An entry that ASKED for a label and got nothing is an option this record
    // does not have — a `{option_d}` on a true/false question. Drop it, rather
    // than falling back to the value and drawing an empty tile labelled "D".
    // An entry with no label key at all is the `["Red", "Blue"]` shorthand and
    // still resolves to its own value below.
    const claimsLabel =
      entry != null &&
      typeof entry === "object" &&
      LABEL_KEYS.some((k) => k in (entry as Record<string, unknown>));
    if (claimsLabel && !label) continue;
    // The VALUE is what a workflow grades against, so it must survive verbatim.
    // Falling back to the label keeps `["Red", "Blue"]` a valid shorthand.
    const rawValue =
      entry && typeof entry === "object" ? (entry as Record<string, unknown>).value : undefined;
    const value =
      typeof rawValue === "string" || typeof rawValue === "number" ? String(rawValue) : label;
    if (label || value) options.push({ value, label: label || value });
  }
  if (options.length < 2) return { ok: false, error: "This puzzle needs at least two options." };
  const columns = Math.min(Math.max(intOf(obj.columns, options.length > 4 ? 3 : 2), 1), 4);
  return { ok: true, spec: { kind: "choices", options, columns } };
}

function parseKeypad(obj: Record<string, unknown>): ParseResult {
  const maxLen = Math.min(Math.max(intOf(obj.max_len ?? obj.maxLen, 6), 1), 12);
  const units = typeof obj.units === "string" && obj.units.trim() ? obj.units.trim() : null;
  return {
    ok: true,
    spec: {
      kind: "keypad",
      maxLen,
      units,
      allowDecimal: boolOf(obj.allow_decimal ?? obj.allowDecimal, false),
      allowSign: boolOf(obj.allow_sign ?? obj.allowSign, false),
    },
  };
}

function parseSequence(obj: Record<string, unknown>): ParseResult {
  const items = asArray(obj.items)
    .slice(0, MAX_ITEMS)
    .map((e) => labelOf(e))
    .filter(Boolean);
  if (items.length < 2) return { ok: false, error: "This puzzle needs at least two steps." };

  // `order` is optional: without it the items are already in the correct order,
  // which is the obvious way to write one by hand. The pad shuffles for display
  // either way, so an author never has to scramble anything themselves.
  const rawOrder = asArray(obj.order);
  const order = rawOrder.length
    ? rawOrder.map((v) => intOf(v, -1))
    : items.map((_, i) => i);
  const valid =
    order.length === items.length &&
    order.every((i) => i >= 0 && i < items.length) &&
    new Set(order).size === order.length;
  if (!valid) return { ok: false, error: "The step order doesn't match the steps." };
  return { ok: true, spec: { kind: "sequence", items, order } };
}

function parseWires(obj: Record<string, unknown>): ParseResult {
  const pairs: WirePair[] = [];
  for (const [i, entry] of asArray(obj.pairs).slice(0, 8).entries()) {
    const rec = (entry && typeof entry === "object" ? entry : {}) as Record<string, unknown>;
    const left = labelOf(rec.left, "left") || labelOf(rec.from, "from");
    const right = labelOf(rec.right, "right") || labelOf(rec.to, "to");
    if (!left || !right) continue;
    const color = typeof rec.color === "string" && rec.color.trim() ? rec.color.trim() : WIRE_COLORS[i % WIRE_COLORS.length];
    pairs.push({ left, right, color });
  }
  if (pairs.length < 2) return { ok: false, error: "This console needs at least two wires." };
  return { ok: true, spec: { kind: "wires", pairs } };
}

function parseSort(obj: Record<string, unknown>): ParseResult {
  const bins = asArray(obj.bins)
    .slice(0, 4)
    .map((e) => labelOf(e))
    .filter(Boolean);
  if (bins.length < 2) return { ok: false, error: "Sorting needs at least two bins." };

  const items: SortItem[] = [];
  for (const entry of asArray(obj.items).slice(0, MAX_ITEMS)) {
    const label = labelOf(entry);
    if (!label) continue;
    const rec = (entry && typeof entry === "object" ? entry : {}) as Record<string, unknown>;
    // A bin may be named or indexed; naming survives reordering the bins, so it
    // is the friendlier form and is checked first.
    const rawBin = rec.bin ?? rec.target;
    let bin = -1;
    if (typeof rawBin === "string") {
      const byName = bins.findIndex((b) => b.toLowerCase() === rawBin.trim().toLowerCase());
      bin = byName >= 0 ? byName : intOf(rawBin, -1);
    } else {
      bin = intOf(rawBin, -1);
    }
    if (bin < 0 || bin >= bins.length) return { ok: false, error: `"${label}" isn't assigned to a bin.` };
    items.push({ label, bin });
  }
  if (!items.length) return { ok: false, error: "Sorting needs at least one item." };
  return { ok: true, spec: { kind: "sort", bins, items } };
}

function parseColor(obj: Record<string, unknown>): ParseResult {
  const palette: PaletteEntry[] = [];
  for (const entry of asArray(obj.palette).slice(0, 8)) {
    if (typeof entry === "string" && entry.trim()) {
      // A bare CSS colour doubles as its own name — `["red", "blue"]` is the
      // shortest thing an author can reasonably write.
      palette.push({ name: entry.trim(), color: entry.trim() });
      continue;
    }
    const rec = (entry && typeof entry === "object" ? entry : {}) as Record<string, unknown>;
    const color = typeof rec.color === "string" ? rec.color.trim() : "";
    const name = labelOf(rec, "name") || color;
    if (color) palette.push({ name, color });
  }
  if (palette.length < 2) return { ok: false, error: "Colouring needs at least two colours." };

  const free = boolOf(obj.free, false);
  const regions: ColorRegion[] = [];
  for (const entry of asArray(obj.regions).slice(0, MAX_ITEMS)) {
    const label = labelOf(entry);
    if (!label) continue;
    const rec = (entry && typeof entry === "object" ? entry : {}) as Record<string, unknown>;
    const rawTarget = rec.target ?? rec.color;
    let target = -1;
    if (!free) {
      if (typeof rawTarget === "string") {
        const t = rawTarget.trim().toLowerCase();
        target = palette.findIndex((p) => p.name.toLowerCase() === t || p.color.toLowerCase() === t);
      } else {
        target = intOf(rawTarget, -1);
        if (target < 0 || target >= palette.length) target = -1;
      }
      if (target < 0) return { ok: false, error: `"${label}" doesn't name a colour from the palette.` };
    }
    regions.push({ label, target });
  }
  if (!regions.length) return { ok: false, error: "Colouring needs at least one region." };
  return { ok: true, spec: { kind: "color", palette, regions, free } };
}

// ------------------------------------------------------------------ //
// Grading — pure over (spec, arrangement). Only for the kinds whose target
// must be sent to the browser to be drawable; see the module note.
// ------------------------------------------------------------------ //

/** Tapped item indices, in tap order, vs the required order. */
export function gradeSequence(spec: SequenceSpec, tapped: number[]): boolean {
  return tapped.length === spec.order.length && tapped.every((v, i) => v === spec.order[i]);
}

/** `connections[leftIndex]` = the right-hand port index it was dragged to, or -1.
 * Correct when every lead lands on its own pair — right ports are displayed in a
 * shuffled order, but the pair index is what identifies them. */
export function gradeWires(spec: WiresSpec, connections: number[]): boolean {
  return spec.pairs.every((_, i) => connections[i] === i);
}

/** `placed[itemIndex]` = the bin it was dropped in, or -1 for still in the tray. */
export function gradeSort(spec: SortSpec, placed: number[]): boolean {
  return spec.items.every((item, i) => placed[i] === item.bin);
}

/** `painted[regionIndex]` = the palette index applied, or -1 for untouched. In
 * free-paint mode every region simply has to be coloured. */
export function gradeColor(spec: ColorSpec, painted: number[]): boolean {
  if (spec.free) return spec.regions.every((_, i) => (painted[i] ?? -1) >= 0);
  return spec.regions.every((region, i) => painted[i] === region.target);
}

/**
 * A short, human-readable record of what the person actually did, reported to
 * the workflow as `answer`. It is what shows up in a mission log or an audit
 * trail, so it names things the way the puzzle did rather than leaking indices.
 */
export function describeArrangement(spec: PuzzleSpec, arrangement: number[]): string {
  switch (spec.kind) {
    case "sequence":
      return arrangement.map((i) => spec.items[i] ?? "?").join(" → ");
    case "wires":
      return spec.pairs
        .map((pair, i) => `${pair.left}→${spec.pairs[arrangement[i]]?.right ?? "—"}`)
        .join(", ");
    case "sort":
      return spec.items
        .map((item, i) => `${item.label}: ${spec.bins[arrangement[i]] ?? "—"}`)
        .join(", ");
    case "color":
      return spec.regions
        .map((region, i) => `${region.label}: ${spec.palette[arrangement[i]]?.name ?? "—"}`)
        .join(", ");
    default:
      return "";
  }
}

/**
 * A display order that stays put across re-renders.
 *
 * Shuffling is what makes an ordering or matching puzzle a puzzle, but it must
 * be stable: a re-shuffle on every keystroke or live refresh would move a target
 * out from under a finger mid-drag. Callers memoise on a spec signature, and the
 * seed makes the result reproducible for tests.
 */
export function stableShuffle(count: number, seed: number): number[] {
  const out = Array.from({ length: count }, (_, i) => i);
  // Mulberry32 — small, fast, and deterministic given the seed.
  let state = seed >>> 0;
  const next = () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(next() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

/** A stable seed for a spec, so the same puzzle shuffles the same way each time
 * it is drawn but two different puzzles don't share an arrangement. */
export function seedFrom(text: string): number {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
